# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 09:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmuserCloning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melting_temperature', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(30)])),
                ('sodium_concentration', models.FloatField(blank=True, null=True)),
                ('primer_concentration', models.FloatField(blank=True, null=True)),
                ('circular_input', models.BooleanField(default=False)),
                ('circular_output', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Casette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('cmd_string', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('ice_id', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primer_suggestion.ProjectBundle'),
        ),
        migrations.AddField(
            model_name='amusercloning',
            name='casette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primer_suggestion.Casette'),
        ),
        migrations.AddField(
            model_name='amusercloning',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='primer_suggestion.Project'),
        ),
    ]
