# Generated by Django 2.0.4 on 2018-04-04 20:31

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmuserCloning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_option', models.IntegerField(choices=[(0, 'none'), (1, 'eq'), (2, 'manual')], default=0)),
                ('melting_temperature', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(30)])),
                ('sodium_concentration', models.FloatField(blank=True, null=True)),
                ('primer_concentration', models.FloatField(blank=True, null=True)),
                ('circular_input', models.BooleanField(default=False)),
                ('circular_output', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Casette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('cmd_string', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CombinatorialProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('parts', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('amusercloning', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combinatorial', to='primer_suggestion.AmuserCloning')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('ice_id', models.PositiveIntegerField(blank=True, default=0)),
                ('amusercloning', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='primer_suggestion.AmuserCloning')),
                ('combinatorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='primer_suggestion.CombinatorialProject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.AddField(
            model_name='amusercloning',
            name='casette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primer_suggestion.Casette'),
        ),
    ]
