# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_suggestion', '0003_combinatorialproject_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='amusercloning',
            name='combinatorial_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primer_suggestion.CombinatorialProject'),
        ),
        migrations.AlterField(
            model_name='amusercloning',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primer_suggestion.Project'),
        ),
    ]
