# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_suggestion', '0004_auto_20170717_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amusercloning',
            name='combinatorial_project',
        ),
        migrations.RemoveField(
            model_name='amusercloning',
            name='project',
        ),
        migrations.AddField(
            model_name='combinatorialproject',
            name='amusercloning',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='primer_suggestion.AmuserCloning'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='amusercloning',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='primer_suggestion.AmuserCloning'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='combinatorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='primer_suggestion.CombinatorialProject'),
        ),
    ]
