# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_suggestion', '0005_auto_20170717_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinatorialproject',
            name='amusercloning',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combinatorial', to='primer_suggestion.AmuserCloning'),
        ),
        migrations.AlterField(
            model_name='project',
            name='amusercloning',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='primer_suggestion.AmuserCloning'),
        ),
    ]
