# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_suggestion', '0009_auto_20170814_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amusercloning',
            name='user',
        ),
    ]
