# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_suggestion', '0010_remove_amusercloning_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combinatorialproject',
            options={'ordering': ['created_date']},
        ),
    ]
