# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_suggestion', '0013_auto_20171208_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amusercloning',
            name='temperature_strategy',
        ),
        migrations.AddField(
            model_name='amusercloning',
            name='temperature_option',
            field=models.IntegerField(choices=[('none', 'none'), ('eq', 'eq'), ('manual', 'manual')], default=0),
        ),
    ]
