# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_suggestion', '0014_auto_20171213_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amusercloning',
            name='temperature_option',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'eq'), (2, 'manual')], default=0),
        ),
    ]
