version: '3'

services:
    backend:
        build: ./backend
        entrypoint: /usr/local/bin/uwsgi --ini /var/www/server/uwsgi.ini
        environment:
            - DJANGO_SETTINGS_MODULE=user_primer_server.settings.docker
        ports:
          - "8008:8000"
        depends_on:
            - db

    db:
        image: postgres:latest
        hostname: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
    redis:
        image: 'redis:latest'