version: '3'

services:
    backend:
        build: ./backend
        entrypoint: bash -c "python manage.py makemigrations && python manage.py migrate && /usr/local/bin/uwsgi --ini /var/www/server/uwsgi.ini"
        ports:
          - "8008:8000"
        depends_on:
            - db

    db:
        image: postgres:latest
        hostname: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres