# Generated by Django 2.0.4 on 2018-04-04 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IceDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(blank=True, max_length=50)),
                ('PASSWORD', models.CharField(blank=True, max_length=50)),
                ('API_USER', models.CharField(blank=True, default='UCloning', max_length=50)),
                ('API_KEY', models.CharField(default='3mEya8B8VjYKsLWuoQoNhaAjLmgxYGITECvpEG/CYdg=', max_length=50)),
                ('HOST', models.CharField(default='ice-1.ice.ba5123dc.cont.dockerapp.io', max_length=50)),
                ('PORT', models.IntegerField(default=32832)),
            ],
        ),
        migrations.CreateModel(
            name='IceUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_token', models.CharField(blank=True, max_length=50, null=True)),
                ('ice_host', models.CharField(default='ice.ebdrup.biosustain.dtu.dk', max_length=50)),
                ('ice_port', models.IntegerField(default=443)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
