# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_authentication', '0002_auto_20171025_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iceuserprofile',
            name='ice_host',
            field=models.CharField(default='ice.ebdrup.biosustain.dtu.dk', max_length=50),
        ),
        migrations.AlterField(
            model_name='iceuserprofile',
            name='ice_port',
            field=models.IntegerField(default=443),
        ),
    ]
