# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(blank=True, max_length=50)),
                ('PASSWORD', models.CharField(blank=True, max_length=50)),
                ('API_USER', models.CharField(blank=True, default='UCloning', max_length=50)),
                ('API_KEY', models.CharField(default='3mEya8B8VjYKsLWuoQoNhaAjLmgxYGITECvpEG/CYdg=', max_length=50)),
                ('HOST', models.CharField(default='ice-1.ice.ba5123dc.cont.dockerapp.io', max_length=50)),
                ('PORT', models.IntegerField(default=32832)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('ice_id', models.IntegerField()),
                ('ice_name', models.CharField(max_length=200)),
                ('fwd_strand', models.BooleanField(default=True)),
            ],
        ),
    ]
