# Generated by Django 2.0.4 on 2018-04-04 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('primer_suggestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('ice_id', models.IntegerField()),
                ('ice_name', models.CharField(max_length=200)),
                ('fwd_strand', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PartHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parthandler', to='primer_suggestion.Project')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='_handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='parts_library.PartHandler'),
        ),
    ]
