# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primer_suggestion', '0001_initial'),
        ('parts_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_username', models.TextField(blank=True)),
                ('ice_password', models.TextField(blank=True)),
                ('PORT', models.IntegerField(default=32832)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parthandler', to='primer_suggestion.Project')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='_handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='parts_library.PartHandler'),
        ),
    ]
