# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_library', '0002_iceuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iceuserprofile',
            name='PORT',
        ),
        migrations.RemoveField(
            model_name='iceuserprofile',
            name='ice_password',
        ),
        migrations.RemoveField(
            model_name='iceuserprofile',
            name='ice_username',
        ),
        migrations.AddField(
            model_name='iceuserprofile',
            name='ice_token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
